# Use the official Python image as the base image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

#COPY services/ /app/services/
COPY shared/ /app/shared/

#COPY vars.env .

# Copy the requirements file into the container
COPY services/requirements_llm.txt .

# Install Python dependencies
RUN pip install -r requirements_llm.txt

# Install Whisper's dependencies (if needed)
RUN apt-get update && apt-get install -y ffmpeg libsndfile1

# Set the FLASK_APP environment variable to point to the Flask application
ENV FLASK_APP=services/llm_api.py

# Add `/app` to the Python path to resolve module imports
ENV PYTHONPATH=/app

# Expose the port for Flask API
EXPOSE 8503

# Start Flask API and Celery worker
CMD ["sh", "-c", "celery -A services.llm_api.celery worker --loglevel=info -Q llm --concurrency=8 & flask run --host=0.0.0.0 --port=8503"]
